spring.application.name=auth-service

spring.datasource.url=jdbc:postgresql://localhost:5432/authdb
spring.datasource.username=${PG_DB_USER}
spring.datasource.password=${PG_DB_PASSWORD}
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.hibernate.ddl-auto=none
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

spring.flyway.enabled=true
spring.flyway.locations=classpath:db/migration

jwt.secret=29cf8f55cc91053b0c992a7d73571b16d2b62b2d24822ac3d01ee5c403ec7016
jwt.expiration=86400000
jwt.header=Authorization
jwt.prefix=Bearer