spring.application.name=auth-service

spring.datasource.url=jdbc:h2:mem:authservice
spring.datasource.driver-class-name=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=

spring.h2.console.enabled=true
spring.h2.console.path=/h2-console
spring.h2.console.settings.web-allow-others=true

spring.jpa.hibernate.ddl-auto=none
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.database-platform=org.hibernate.dialect.H2Dialect

spring.flyway.enabled=true
spring.flyway.locations=classpath:db/migration

jwt.secret=29cf8f55cc91053b0c992a7d73571b16d2b62b2d24822ac3d01ee5c403ec7016
jwt.expiration=3600000
jwt.header=Authorization
jwt.prefix=Bearer